// @title Warm-Flow PoC BFF API
// @version 1.0
// @description Internal gateway: mock business DB, CC audit, and Warm-Flow HTTP proxy. Send X-API-KEY on /internal/poc/warm-flow/* (see Authorize in Swagger UI).
// @termsOfService http://swagger.io/terms/
//
// @contact.name API Support
//
// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
//
// @host localhost:8080
// @BasePath /
// @schemes http
//
// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name X-API-KEY
package main

import (
	"log"
	"net/http"
	"os"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	"gorm.io/driver/mysql"
	"gorm.io/gorm"

	_ "brm-poc-lab/gateway/docs" // generated by swag
)

func main() {
	dsn := os.Getenv("MYSQL_DSN")
	if dsn == "" {
		dsn = "root:pocroot@tcp(mysql:3306)/ttpos_poc_biz?charset=utf8mb4&parseTime=True&loc=Local"
	}
	apiKey := os.Getenv("INTERNAL_API_KEY")
	if apiKey == "" {
		apiKey = "dev-poc-key"
	}
	wfBase := os.Getenv("WARM_FLOW_BASE_URL")
	if wfBase == "" {
		wfBase = "http://warm-flow:8081"
	}
	jwtSecret := os.Getenv("TTPOS_JWT_SECRET")
	if jwtSecret == "" {
		// Matches main/tests/test.env in ttpos-server-go.
		jwtSecret = "test-secret-key-for-integration-tests"
	}
	ttposDsnFmt := os.Getenv("TTPOS_DSN_FMT")
	if ttposDsnFmt == "" {
		ttposDsnFmt = "root:pocroot@tcp(mysql:3306)/shop%d?charset=utf8mb4&parseTime=True&loc=Local"
	}

	db, err := gorm.Open(mysql.Open(dsn), &gorm.Config{})
	if err != nil {
		log.Fatalf("db: %v", err)
	}
	wf := newWFClient(wfBase)
	ttposDB := newTtposDBManager(ttposDsnFmt)
	srv := NewServer(db, wf, apiKey, jwtSecret, ttposDB)

	gin.SetMode(gin.ReleaseMode)
	r := gin.New()
	r.Use(gin.Recovery())

	srv.Register(r)
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	addr := ":8080"
	if p := os.Getenv("PORT"); p != "" {
		addr = ":" + p
	}
	log.Printf("gateway listening %s (open /swagger/index.html for API docs)", addr)
	if err := r.Run(addr); err != nil && err != http.ErrServerClosed {
		log.Fatal(err)
	}
}
