// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Returns plain text ok",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "public"
                ],
                "summary": "Liveness",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/internal/poc/warm-flow/cc-record": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns the latest 50 CC rows, newest first. Optional query businessId filters to one order. For debugging and PoC verification.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "internal"
                ],
                "summary": "List CC records",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API key",
                        "name": "X-API-KEY",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filter by business id",
                        "name": "businessId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/main.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/main.PocCcEvent"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/main.Envelope"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Persists one CC (carbon-copy) audit row when the engine fires a CC / notify step. Body: businessId, nodeCode, timing, ccUserIds array. Stored in poc_cc_event as JSON text for ccUserIds.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "internal"
                ],
                "summary": "Record CC event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API key",
                        "name": "X-API-KEY",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Payload",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.ccRecordReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/main.Envelope"
                        }
                    }
                }
            }
        },
        "/internal/poc/warm-flow/flow-finished": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Java TaskListener invokes this when the flow instance ends. Sets poc_mock_transfer_order.status for the given businessId (order no). Body status defaults to approved if empty (e.g. completed path).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "internal"
                ],
                "summary": "Flow finished callback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API key",
                        "name": "X-API-KEY",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Payload",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.flowFinishedReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.Envelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/main.Envelope"
                        }
                    }
                }
            }
        },
        "/internal/poc/warm-flow/resolve-approver": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Warm-Flow calls this webhook to resolve handler user IDs for a node. PoC: looks up mock transfer order by businessId (order no), then for roleCode RECEIVER_MANAGER returns the receiving shop's region_manager_user_id from poc_mock_shop.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "internal"
                ],
                "summary": "Resolve approvers by business + role",
                "parameters": [
                    {
                        "type": "string",
                        "default": "dev-poc-key",
                        "description": "API key",
                        "name": "X-API-KEY",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Payload",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.resolveReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/main.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/main.resolveData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/main.Envelope"
                        }
                    }
                }
            }
        },
        "/internal/poc/warm-flow/task/cancel": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Proxies to Warm-Flow POST /api/task/cancel. Cancels the instance (PoC TB-1004). Same body shape as terminate: taskId, handler, message.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "internal"
                ],
                "summary": "Cancel task / flow",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API key",
                        "name": "X-API-KEY",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Payload",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.wfTerminateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/main.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": true
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/main.Envelope"
                        }
                    }
                }
            }
        },
        "/internal/poc/warm-flow/task/skip": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Proxies to Warm-Flow POST /api/task/skip. Use to approve/pass the current human task (taskId, handler, message; skipType optional). Do not use for reject—use /task/terminate instead for PoC reject path.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "internal"
                ],
                "summary": "Skip / approve task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API key",
                        "name": "X-API-KEY",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Payload",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.wfSkipReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/main.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": true
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/main.Envelope"
                        }
                    }
                }
            }
        },
        "/internal/poc/warm-flow/task/terminate": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Proxies to Warm-Flow POST /api/task/terminate. Ends the instance with reject-style termination (PoC TB-1003). Updates downstream status via flow-finished when engine completes.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "internal"
                ],
                "summary": "Terminate task (reject)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API key",
                        "name": "X-API-KEY",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Payload",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.wfTerminateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/main.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": true
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/main.Envelope"
                        }
                    }
                }
            }
        },
        "/internal/poc/warm-flow/tasks/todo": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Calls Warm-Flow GET /api/task/todo?handler=userId, then enriches each task with amount, fromShop, and toShop from poc_mock_transfer_order. Use this BFF endpoint for an approval todo list in client apps instead of calling Warm-Flow directly.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "internal"
                ],
                "summary": "Aggregated todo list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API key",
                        "name": "X-API-KEY",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Handler user id",
                        "name": "userId",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/main.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/main.aggregatedTodoItem"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/main.Envelope"
                        }
                    }
                }
            }
        },
        "/internal/poc/warm-flow/transfer/submit-start": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Sets mock order status to approving, then POSTs /api/flow/start to Warm-Flow with businessId=orderNo, flowCode, handler=createBy, and variables (including optional ccUserIds as array). Returns engine JSON inside envelope data on success. Typical first call from app when submitting a transfer for approval.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "internal"
                ],
                "summary": "Start transfer flow",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API key",
                        "name": "X-API-KEY",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Payload",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.submitStartReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/main.Envelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": true
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/main.Envelope"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.Envelope": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "main.PocCcEvent": {
            "type": "object",
            "properties": {
                "businessId": {
                    "type": "string"
                },
                "ccUserIds": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nodeCode": {
                    "type": "string"
                },
                "timing": {
                    "type": "string"
                }
            }
        },
        "main.aggregatedTodoItem": {
            "type": "object",
            "properties": {
                "fromShop": {
                    "type": "string"
                },
                "nodeCode": {
                    "type": "string"
                },
                "orderAmount": {
                    "type": "integer"
                },
                "orderNo": {
                    "type": "string"
                },
                "taskId": {
                    "type": "integer"
                },
                "taskName": {
                    "type": "string"
                },
                "toShop": {
                    "type": "string"
                }
            }
        },
        "main.ccRecordReq": {
            "type": "object",
            "properties": {
                "businessId": {
                    "type": "string"
                },
                "ccUserIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "nodeCode": {
                    "type": "string"
                },
                "timing": {
                    "type": "string"
                }
            }
        },
        "main.flowFinishedReq": {
            "type": "object",
            "properties": {
                "businessId": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "main.resolveData": {
            "type": "object",
            "properties": {
                "userIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "main.resolveReq": {
            "type": "object",
            "properties": {
                "businessId": {
                    "type": "string"
                },
                "roleCode": {
                    "type": "string"
                },
                "variables": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "main.submitStartReq": {
            "type": "object",
            "properties": {
                "ccUserIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "createBy": {
                    "type": "string"
                },
                "flowCode": {
                    "type": "string"
                },
                "orderNo": {
                    "type": "string"
                },
                "variables": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "main.wfSkipReq": {
            "type": "object",
            "properties": {
                "handler": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "skipType": {
                    "type": "string"
                },
                "taskId": {
                    "type": "integer"
                }
            }
        },
        "main.wfTerminateReq": {
            "type": "object",
            "properties": {
                "handler": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "taskId": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-API-KEY",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Warm-Flow PoC BFF API",
	Description:      "Internal gateway: mock business DB, CC audit, and Warm-Flow HTTP proxy. Send X-API-KEY on /internal/poc/warm-flow/* (see Authorize in Swagger UI).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
